language: java
before_script:
  - mvn clean install -pl . -Dmaven.test.skip=true
  - mvn clean install -pl . -Dmaven.test.skip=true
  - mvn clean install -pl .  -Dmaven.test.skip=true

script:
  - mvn test

jdk:
  - openjdk7
notifications:
  email:
    - zhangkaitao0503@gmail.com