language: java


jdk:
  - openjdk



install:
  - mvn install -Dmaven.test.skip=true


script:
  - cd common
  - mvn test
  - cd ..
  - cd web
  - mvn test -Ptest



notifications:
  email:
    - zhangkaitao0503@gmail.com