language: java

env:
  - DB=mysql

jdk:
  - openjdk7

mysql:
  database: es
  username: root
  password :
  encoding: utf8

install:
  - mvn install -Dmaven.test.skip=true

before_script:
  - cd web
  - mvn db:create
  - mvn db:schema
  - mvn db:data
  - cd ..

##
#顺序只能是web 然后common 好像是travis环境的问题
##

script:
  - cd web
  - mvn test
  - cd ..
  - cd common
  - mvn test


notifications:
  email:
    - zhangkaitao0503@gmail.com