language: java

env:
  - DB=mysql

jdk:
  - openjdk7

mysql:
  adapter: mysql2
  database: es
  port : 3306
  username: root
  password :
  encoding: utf8

script:
  - mvn test

notifications:
  email:
    - zhangkaitao0503@gmail.com