language: java

env:
  - DB=mysql

jdk:
  - openjdk7

before_script:
  - mvn db:create
  - mvn db:schema
  - mvn db:data

install:
  - mvn clean install -pl . -Dmaven.test.skip=true
  - mvn clean install -pl parent -Dmaven.test.skip=true
  - mvn clean install -pl common -Dmaven.test.skip=true

script:
  - mvn test

notifications:
  email:
    - zhangkaitao0503@gmail.com