language: java
before_script:
  - mvn clean install -pl . -Dmaven.test.skip=true
  - mvn -o clean install -pl parent -Dmaven.test.skip=true
  - mvn -o clean install -pl common -Dmaven.test.skip=true

script:
  - mvn -o test

jdk:
  - openjdk7
notifications:
  email:
    - zhangkaitao0503@gmail.com