language: java
install:
  - mvn clean install -pl . -Dmaven.test.skip=true
  - mvn clean install -pl parent -Dmaven.test.skip=true
  - mvn clean install -pl common -Dmaven.test.skip=true

script:
  - mvn test

jdk:
  - openjdk7
notifications:
  email:
    - zhangkaitao0503@gmail.com